version: '3.3'

services:
  backend:
    build:
      context: ./flask-backend
      dockerfile: Dockerfile
      args:
        BUILD_TIME: ${BUILD_TIME}
        DYNAMIC_PARAM: ${DYNAMIC_PARAM}
    ports:
      - "${BACKEND_PORT}:5000"
    environment:
      - BUILD_TIME=${BUILD_TIME}
      - DYNAMIC_PARAM=${DYNAMIC_PARAM}
      - FLASK_ENV=production
      - BACKEND_PORT=${BACKEND_PORT}

  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
