version: '3.3'

services:
  backend:
    build:
      context: ./flask-backend
      dockerfile: Dockerfile
      args:
        BUILD_TIME: ${BUILD_TIME}
        DYNAMIC_PARAM: ${DYNAMIC_PARAM}
    ports:
      - "5000:5000"
    environment:
      - BUILD_TIME=${BUILD_TIME}
      - DYNAMIC_PARAM=${DYNAMIC_PARAM}
      - FLASK_ENV=production

  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
